community:
  HDD: 14593
  current year: 2014
  diesel generation efficiency: 10.802351555
  diesel prices: IMPORT
  discount rate: 0.03
  elec non-fuel cost: 0.4024526823
  heating fuel premium: 0.45
  interest rate: 0.05
  line losses: 0.121
  name: Manley Hot Springs
  region: Yukon-Koyukuk/Upper Tanana
  res non-PCE elec cost: 0.83
community buildings:
  average refit cost: 7.0
  cohort savings multiplier: 0.26
  com benchmark data: IMPORT
  com building estimates: IMPORT
  com num buildings: IMPORT
  enabled: true
  lifetime: 10
  start year: 2015
construction multipliers:
  Aleutians: 1.4
  Bering Straits: 1.8
  Bristol Bay: 1.25
  Copper River/Chugach: 1.1
  Kodiak: 1.18
  Lower Yukon-Kuskokwim: 1.6
  North Slope: 1.8
  Northwest Arctic: 1.7
  Southeast: 1.15
  Yukon-Koyukuk/Upper Tanana: 1.4
forecast:
  electricity: IMPORT
  end year: 2040
  population: IMPORT
residential buildings:
  average refit cost: 11000
  enabled: true
  lifetime: 15
  res model data: IMPORT
  start year: 2015
water wastewater:
  audit cost: 10000
  audit preformed: false
  average refit cost: 360.0
  collected data: IMPORT
  enabled: true
  energy use known: false
  heat recovery multiplier:
    false: 1.0
    true: 0.5
  heat recovery used: false
  lifetime: 15
  start year: 2015
  system type: Haul
  ww assumptions: IMPORT
