community:
  HDD: 14593
  consumption HF: 35865.0
  current year: 2014
  diesel generation efficiency: 10.802351555
  diesel prices: IMPORT
  discount rate: 0.03
  elec non-fuel cost: 0.545731747669
  electric non-fuel prices: IMPORT
  generation: 449710.0
  heating fuel premium: 1.5507921943
  interest rate: 0.05
  line losses: 0.121
  model financial: true
  name: Manley Hot Springs
  region: Yukon-Koyukuk/Upper Tanana
  res non-PCE elec cost: 0.916675
community buildings:
  average refit cost: 7.0
  cohort savings multiplier: 0.26
  com building data: IMPORT
  com building estimates: IMPORT
  enabled: true
  lifetime: 10
  number buildings: 21
  start year: 2015
construction multipliers:
  Aleutians: 1.4
  Bering Straits: 1.8
  Bristol Bay: 1.25
  Copper River/Chugach: 1.1
  Kodiak: 1.18
  Lower Yukon-Kuskokwim: 1.6
  North Slope: 1.8
  Northwest Arctic: 1.7
  Southeast: 1.15
  Yukon-Koyukuk/Upper Tanana: 1.4
forecast:
  electricity: IMPORT
  end year: 2040
  population: IMPORT
residential buildings:
  average refit cost: 11000
  data: IMPORT
  enabled: true
  lifetime: 15
  start year: 2015
water wastewater:
  audit cost: 10000
  average refit cost: 360.0
  data: IMPORT
  electricity refit reduction: 0.25
  enabled: true
  heat recovery multiplier:
    false: 1.0
    true: 0.5
  heating fuel refit reduction: 0.35
  lifetime: 15
  start year: 2015
