community: 
  current year: 2014 #year to base npv calculations on <int>
  interest rate: .05 # rate as decimal <float> (ex. .05) 
  discount rate: .03 # rate as decimal <float> (ex. .03)
   
  #do these come from community profiles?
  generation: 440077.00 # kWh generated/yr  <float> 123456.00
  #consumption kWh: 384000.00 # kWh consumed/year <float> 12345.00
  consumption HF: 40739.00 # gallons HF consumed/year <float> 12345.00
  res non-PCE elec cost: 00.83 # $cost/kWh <float> .83
  line losses: .1210 #rate as decimal <float> (ex. .1210)

  elec non-fuel cost: 0.4024526823 # TODO: should be calculated

forecast:
  end year: 2040 # end year <int>

residential buildings: 
  enabled: True
  lifetime: 15 # number years <int>  
  start year: 2015 # start year <int>

community buildings:
  enabled: True
  lifetime: 10 # number years <int>  
  start year: 2015 # start year <int>

water wastewater:
  enabled: True
  lifetime: 15 # number years <int>  
  start year: 2015 # start year <int>
